# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    m2_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

m2_arm_controller:
  ros__parameters:
    joints:
      - base_to_L1
      - L1_to_L2
      - L2_to_L3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    joints:
      - L3_to_L4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity